// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/link.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CallScrapeServiceClient is the client API for CallScrapeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CallScrapeServiceClient interface {
	CallScrape(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type callScrapeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCallScrapeServiceClient(cc grpc.ClientConnInterface) CallScrapeServiceClient {
	return &callScrapeServiceClient{cc}
}

func (c *callScrapeServiceClient) CallScrape(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.CallScrapeService/CallScrape", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallScrapeServiceServer is the server API for CallScrapeService service.
// All implementations must embed UnimplementedCallScrapeServiceServer
// for forward compatibility
type CallScrapeServiceServer interface {
	CallScrape(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedCallScrapeServiceServer()
}

// UnimplementedCallScrapeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCallScrapeServiceServer struct {
}

func (UnimplementedCallScrapeServiceServer) CallScrape(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallScrape not implemented")
}
func (UnimplementedCallScrapeServiceServer) mustEmbedUnimplementedCallScrapeServiceServer() {}

// UnsafeCallScrapeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallScrapeServiceServer will
// result in compilation errors.
type UnsafeCallScrapeServiceServer interface {
	mustEmbedUnimplementedCallScrapeServiceServer()
}

func RegisterCallScrapeServiceServer(s grpc.ServiceRegistrar, srv CallScrapeServiceServer) {
	s.RegisterService(&CallScrapeService_ServiceDesc, srv)
}

func _CallScrapeService_CallScrape_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallScrapeServiceServer).CallScrape(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CallScrapeService/CallScrape",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallScrapeServiceServer).CallScrape(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// CallScrapeService_ServiceDesc is the grpc.ServiceDesc for CallScrapeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CallScrapeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CallScrapeService",
	HandlerType: (*CallScrapeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallScrape",
			Handler:    _CallScrapeService_CallScrape_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/link.proto",
}
