apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application-ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/auth-method: GET
    nginx.ingress.kubernetes.io/auth-url: http://pricey.com/api/verify
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/custom-headers: |
      proxy_set_header Authorization $Authorization;
    nginx.ingress.kubernetes.io/auth-response-headers: UserId
spec:
  rules:
    - host: pricey.com
      http:
        paths:
          - path: /api/link
            pathType: Prefix
            backend:
              service:
                name: link-clusterip-srv
                port:
                  number: 8081
          
     